apiVersion: v1
kind: Secret
metadata:
  name: narrati-backend-secrets
  namespace: narrati-staging
type: Opaque
# echo -n "root" | base64
# echo -n "example" | base64
data:
  reddit_username: No_Motor4670
  reddit_password: 9ihj85cKafBDhnz
  client_secret: kEwrZ1lE7CBG3bO1GrUKBE7w1h7KrA
  client_id: kHJKrExaUX1LVN2X6l2FKQ
  rapid_host: twitter154.p.rapidapi.com
  rapid_key: af84b1bf59msh17cad9f3c2f94a4p1586d9jsn4ce6d0296a07

#comment to restart deployment
