
apiVersion: v1
kind: ConfigMap
metadata:
  name: narrati-staging-configmap
  namespace: narrati-staging
data:
  # https://stackoverflow.com/questions/49129809/kubernetes-how-to-send-data-from-a-pod-to-another-pod-in-kubernetes
  react-app-server-base: http://narrati-staging-backend-service.narrati-staging
  react-app-server-port: "8080"
  mongo-initdb-database: task-management
  mongo-port-for-backend: "27017"
  mongo-host-for-backend: narrati-staging-mongo-service.narrati-staging

